# Generated by Django 5.2.4 on 2025-09-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='Emotion',
            new_name='emotion',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='DateTime',
            new_name='dateTime',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='EmotionalStatus',
        ),
        migrations.AddField(
            model_name='journal',
            name='emotionalStatus',
            field=models.ManyToManyField(related_name='Mood', to='journal.emotion'),
        ),
    ]
