# Generated by Django 5.2.4 on 2025-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
