# Generated by Django 5.2.4 on 2025-08-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0002_course_updated_at_track_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
