# Generated by Django 5.2.4 on 2025-07-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_authenticated_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_authenticated',
            new_name='authenticated',
        ),
    ]
