# Generated by Django 5.2.4 on 2025-08-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
        ('user', '0006_rename_is_authenticated_user_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.ManyToManyField(to='meditation.tag'),
        ),
    ]
