# Generated by Django 5.2.4 on 2025-09-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='sunrise', max_length=100),
        ),
    ]
