# Generated by Django 5.2.4 on 2025-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
