# Generated by Django 5.2.4 on 2025-09-22 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('meditation', '0004_tag_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='meditation_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('duration', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meditation_course_sessions', to='meditation.course')),
                ('endingingEmotion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_emotion', to='journal.emotion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_sessions', to=settings.AUTH_USER_MODEL)),
                ('startingEmotion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initial_emotion', to='journal.emotion')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='meditation.track')),
            ],
        ),
    ]
