# Generated by Django 5.2.4 on 2025-09-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditationsessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meditation_session',
            old_name='endingingEmotion',
            new_name='final_emotion',
        ),
        migrations.RenameField(
            model_name='meditation_session',
            old_name='startingEmotion',
            new_name='initial_emotion',
        ),
    ]
